MUSTAFA-A-KHAN/telegram-bot-anime

controller/bot.go

fix: uncomment startHttpServer

---

controller/bot.go

add spacing to showcase explain button

Add spacing to showcase explain button

---

controller/bot.go

Successfully mention the user without username as well.

feat: correctly mention the leader.

---

controller/bot.go
view/response.go

When new game will begin bot will respond with a sticker.

Bot respond with a sticker at the start.

---

controller/bot.go
view/response.go

Reverts MUSTAFA-A-KHAN/telegram-bot-anime#16

Revert "Bot respond with a sticker at the start."

---

controller/bot.go
view/response.go

Reverts MUSTAFA-A-KHAN/telegram-bot-anime#17

Revert "Revert "Bot respond with a sticker at the start.""

---

controller/bot.go
view/response.go

Reverts MUSTAFA-A-KHAN/telegram-bot-anime#18

Revert "Revert "Revert "Bot respond with a sticker at the start."""

---

controller/bot.go
view/response.go

Reverts MUSTAFA-A-KHAN/telegram-bot-anime#19

Revert "Revert "Revert "Revert "Bot respond with a sticker at the start.""""

---

controller/bot.go

Now user can report the feedback to the admin via using /report command

feat: add report feature, increase wait time for next leader.

---

controller/bot.go

There won't be any leader upon pressing next button.

fix: no new leader upon next button

---

controller/instagramBot/bot.go
main.go
model/instagram_userInfo.go

this bot scrapes the latest video of a userame from the instagram.

feat: add another instagram scrapperbot

---

controller/instagramBot/bot.go

Add error response to the user chat.

feat: add error response upon failure

---

controller/instagramBot/bot.go
model/instagram_userInfo.go
repository/dbManager.go

Add instagram bot

---

service/getInstagram.go
service/getSessionService.go

get cookie from confg and then do the job.!!!!!!!!

feat: add session handle via cookie from config.

---

controller/bot.go
controller/categoryBot/categoryBot.go

Update the chatstate to use id for assigning a leader

refactor: use ID instead of username for leadership.

---

controller/bot.go
controller/categoryBot/categoryBot.go

Reverts MUSTAFA-A-KHAN/telegram-bot-anime#30

Revert "refactor: use ID instead of username for leadership."

---

model/anime.go

This will get words from our own json file which we can modify or update for new words.

feat: get words from personal json.

---

controller/bot.go

Made it so the leader stays the leader if they peek at the word. No accidental leadership swaps here! 💪✨

fix: no new leader if the leader himslef click see word.

---

controller/bot.go
controller/categoryBot/categoryBot.go

Bot session now works with player IDs instead of usernames, allowing users without usernames to play. 🎮🚀

refactor: use ID instead of username.

---

controller/bot.go
controller/categoryBot/categoryBot.go
repository/dbManager.go
service/leaderBoardList.go

"Flex your grind 💪 with the new leaderboard feature—now you can track the legends at the top and aim for the crown. 'Leaderboard' means a chart that shows who's boss and who's chasing the win. Keep climbing, fam!"

feat: add leaderboard for leader as well.

---

controller/bot.go
controller/categoryBot/categoryBot.go

Yo fam, this update is 🔥! We’re now using Goroutines to handle every new message like a boss. 🚀
What’s New:
Goroutine Glow-Up: Each message gets its own Goroutine, so we’re all about that parallel vibes now. 🕺
Big Brain Scalability: System’s ready to handle more traffic than your Wi-Fi during a Netflix binge. 📈
No Crash Zone: Built-in error handling so we don’t yeet the whole app when something goes wrong. 🤝
Clean Code FTW: Tidied up the codebase to make it smooth and future-proof. 💅
Why This Slaps:
Replies are faster than your best comebacks. ⚡
We’re scaling like it’s a rock-climbing comp. 🧗‍♂️
Maintenance? Easy peasy lemon squeezy. 🍋

enhancement: imrove response ping using go routines.

---

controller/bot.go

Reverts MUSTAFA-A-KHAN/telegram-bot-anime#44

Revert "Feature/reveal unguessed word"

---

controller/bot.go

Add per-person-stats for the GC

feat: add gc my stats
